---
stages:
  - test
  - build
  - publish
  - trigger-upload

include:
  - project: saltstack/pop/cicd/ci-templates
    file: /docswork/url-tester-brok.yml
  - project: saltstack/pop/cicd/ci-templates
    file: /docswork/publish-docs-gitlab.yml
  - project: saltstack/pop/cicd/ci-templates
    file: /docswork/salt-publish-docs-release.yml

variables:
  CICD_UPSTREAM_PATH: "saltstack/open/docs/salt-install-guide"
  # LATEST_DOCS_VERSION: '3005'
  # GIT_STRATEGY: clone
  # GIT_DEPTH: 0

url-tester-brok:
  stage: test

pre-commit:
  stage: test
  image: python:3.8-buster
  variables:
    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/pre-commit-cache"
  cache:
    key: pre-commit-cache
    paths:
      - pre-commit-cache/
  script:
    - pip install -U pip setuptools wheel
    - pip install -r requirements-dev.txt
    - pre-commit install
    - pre-commit run -a -v --color always

build-site:
  stage: build
  image: python:3.8
  script:
    - pip install -U pip setuptools wheel
    - pip install -r requirements-dev.txt
    - wget -O docs/_static/img/SaltProject_altlogo_teal.png https://gitlab.com/saltstack/open/salt-branding-guide/-/raw/master/logos/SaltProject_altlogo_teal.png?inline=false
    - wget -O docs/_static/img/SaltProject_Logomark_teal.png https://gitlab.com/saltstack/open/salt-branding-guide/-/raw/master/logos/SaltProject_Logomark_teal.png?inline=false
    - nox -e 'docs-html(clean=True)'
    - mv docs/_build/html html
  artifacts:
    paths:
      - html
    expire_in: 30 days

pages:
  stage: publish

publish-docs:
  stage: trigger-upload
  variables:
    CICD_S3_DEST_PATH: "docs.saltproject.io/salt/install-guide/"

#trigger-upload:
#  stage: trigger-upload
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == $CICD_UPSTREAM_PATH'
#  variables:
#    ARTIFACT_PIPELINE_ID: $CI_PIPELINE_ID
#    GITLAB_PROJECT_PATH: "saltstack%2Fopen%2Fdocs%2Fsalt-install-guide"
#    DOCS_PATH: "docs.saltproject.io/salt/install-guide/en"
#    RCLONE_OPTIONS: "sync -c -v"
#  trigger:
#    project: saltstack/open/docs/docs-upload
#    strategy: depend
